name: Build and Deploy to Pi
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & build
        run: |
          npm ci
          npm run build
      - name: Deploy dist/ via rsync
        uses: burnett01/rsync-deployments@6.0
        with:
          switches: -avz --delete
          path: dist/
          remote_path: /var/www/reactapp/
          remote_host: ${{ secrets.PI_HOST }}
          remote_user: ${{ secrets.PI_USER }}
          remote_key:  ${{ secrets.PI_SSH_KEY }}
      - name: Reload Caddy
        run: |
          echo "${{ secrets.PI_SSH_KEY }}" > key && chmod 600 key
          ssh -o StrictHostKeyChecking=no -i key ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} 'sudo systemctl reload caddy'
